"""exp06 — PAPER generator: builds docs/PAPER_RESULTS.md from results/run-*.json.

Structure follows AlgoXpert IS–WFA–OOS + WFER + Monte Carlo + Minerva/DSR-PBO-SPA-MinTRL
reporting (see docs/SOURCES.md §J–K). No new statistics invented here — only tabulates
frozen-spec runs with provenance + limits. Deterministic.
"""
import os, sys, json, glob
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))

runs = {}
for p in sorted(glob.glob("results/run-*.json")):
    with open(p) as f:
        runs[p] = json.load(f)

def g(p, *keys, default="—"):
    d = runs.get(p, {})
    for k in keys:
        if isinstance(d, dict) and k in d:
            d = d[k]
        else:
            return default
    return d

L = []
L.append("# PAPER RESULTS — Creamer 4-step frozen-spec verification (public data)")
L.append("")
L.append("> Generated by `src/exp06_paper.py` from `results/run-*.json`. Seed 7. Hypothetical (CFTC 4.41).")
L.append("> Not financial advice. Tape (bid/ask) + GEX feed remain TODO — absorption unproven.")
L.append("")
L.append("## 1. Question")
L.append("Does the transcript-frozen 4-step (HTF value + naive-GEX regime → VA/fib-705/788/886 discount "
         "outside VA → footprint absorption + 2nd-fail + flip → 1.5R to POC/VAH, 20k/90-min/2-loss filters) "
         "survive public-data, cost-aware, benchmark-deflated testing, or fail like most retail systems?")
L.append("")
L.append("## 2. Data (public only)")
L.append("| Exp | Provenance | n bars |")
L.append("|---|---|---|")
for p, d in runs.items():
    L.append(f"| {d.get('exp','?')} | {str(d.get('provenance', d.get('proxy', '')))[:90]} | {d.get('n', d.get('location_hits','—'))} |")
L.append("")
L.append("Free-public ladder used: yfinance NQ=F 5m/60d → Stooq nq.f daily → synthetic fallback "
         "(marked). Paid Level1 tape (Portara/CQG, Databento, FirstRate, Barchart) is the only true "
         "footprint source and was NOT purchased — hence proxy-honest limits throughout.")
L.append("")
L.append("## 3. Results (frozen v1.0, next-open, stop-first, costs gross+net)")
L.append("| Exp | n trades/hits | PF net | Expect/R | MaxDD_R | Note |")
L.append("|---|---|---|---|---|---|")
L.append(f"| exp00 synthetic | {g('results/run-v1.0-exp00-synthetic-seed7.json','n')} | "
         f"{g('results/run-v1.0-exp00-synthetic-seed7.json','pf_net')} | "
         f"{g('results/run-v1.0-exp00-synthetic-seed7.json','expect_R')} | "
         f"{g('results/run-v1.0-exp00-synthetic-seed7.json','maxDD_R')} | pipeline only |")
L.append(f"| exp01 NQ=F daily | {g('results/run-v1.0-exp01-proxy-seed7.json','n')} | "
         f"{g('results/run-v1.0-exp01-proxy-seed7.json','pf_net')} | "
         f"{g('results/run-v1.0-exp01-proxy-seed7.json','expect_R')} | "
         f"{g('results/run-v1.0-exp01-proxy-seed7.json','maxDD_R')} | SMALL-n, daily≠footprint |")
for k in ("base", "x1.5", "x2"):
    d = runs.get("results/run-v1.0-exp04-public5m-seed7.json", {}).get(k, {})
    L.append(f"| exp04 public-5m {k} | {runs.get('results/run-v1.0-exp04-public5m-seed7.json',{}).get('location_hits','—')} hits "
             f"| {d.get('pf_net','—')} | {d.get('expect_R','—')} | {d.get('maxDD_R','—')} | RTH-filtered bars |")
L.append("")
L.append("## 4. Benchmarks (same bars, exp05)")
b = runs.get("results/run-v1.0-exp05-benchmarks-seed7.json", {})
L.append(f"- Sharpe (5m-ann): `{json.dumps(b.get('sharpe_5m_ann',{}))}`")
L.append(f"- Creamer PSR vs 0: `{b.get('creamer',{}).get('PSR_vs_0','—')}`, "
         f"DSR (4 trials): `{b.get('creamer',{}).get('DSR_trials4','—')}`, "
         f"SR0 noise ceiling: `{b.get('creamer',{}).get('SR0_noise_ceiling','—')}`")
L.append(f"- RC-lite p vs buy-hold: `{json.dumps(b.get('RC_lite_p_vs_buyhold',{}))}`, "
         f"field-max p: `{b.get('RC_field_max_p','—')}`")
L.append(f"- SPA-type p: `{json.dumps(b.get('SPAtype_p_vs_buyhold',{}))}`, "
         f"PBO-lite (4-fold CSCV): `{b.get('PBO_lite_4fold','—')}`")
L.append("- Reading (Bailey-Lopez/White/Hansen): DSR<0.95 or RC p>0.05 ⇒ consistent with luck; "
         "PBO>0.5 ⇒ selection procedure overfits. See §6 verdict.")
L.append("")
L.append("## 5. Costs")
L.append("MNQ tick $0.50, 1-tick slip + $0.60/side base; ×1.5/×2 sensitivity in exp03/exp04. "
         "Strategy must stay PF>1.0 net at ×2 or verdict FAIL.")
L.append("")
L.append("## 6. Verdict (GO/HOLD/REJECT per SPEC §7)")
L.append("**REJECT as edge on public bars; HOLD as research program.** Location arithmetic runs, "
         "filters cut drawdown, but n is small, absorption/GEX unproven without paid tape+chain, "
         "and benchmark-deflated stats do not clear. Advance ONLY via: 1m NQ 2022–26 + 2026 holdout, "
         "tick-aware fills, 25k Monte Carlo, purged rolling WFA (majority-pass + veto), 30d/30-trade replay "
         "adherence≥85%, 90d micro paper within ±0.1R.")
L.append("")
L.append("## 7. Threats")
L.append("- Single-month championship regime; small-n; discretionary gaps (news/psych levels).")
L.append("- Stale GEX (settled vs flow after 11am), MNQ-vs-NQ mismatch, yfinance/Stooq proxy ≠ CME tape.")
L.append("- Correlated-grid effective-N trap: report DSR band, pair with RC (needs no N).")
L.append("- Bar-path R proxy in exp05 ≠ filled trades — use filled-trade field for paper.")
L.append("")
L.append("## 8. Reproduce")
L.append("`pip install -r requirements.txt && python3 src/exp00_synthetic.py && "
         "python3 src/exp01_historical.py && python3 src/exp02_live.py && "
         "python3 src/exp03_improved.py && python3 src/exp04_public_intraday.py && "
         "python3 src/exp05_benchmarks.py && python3 src/exp06_paper.py`")
L.append("")
os.makedirs("docs", exist_ok=True)
with open("docs/PAPER_RESULTS.md", "w") as f:
    f.write("\n".join(L) + "\n")
print("wrote docs/PAPER_RESULTS.md from", len(runs), "runs")
